---
root: true
# https://eslint.org/docs/rules/
env:
  node: true
  es2020: true
parserOptions:
  ecmaVersion: 2020
plugins:
  - jest
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
  - prettier
rules:
  jest/no-done-callback: off
