export const TRACK_FIELD_TYPE = Object.freeze({
  STRING: "STRING",
  INTEGER: "INTEGER",
  FLOAT: "FLOAT",
  TIMESTAMP: "TIMESTAMP",
});

export const TRACK_FIELD_INPUT = Object.freeze({
  TEXT_FIELD: "TEXT_FIELD",
  SELECT: "SELECT",
  SLIDER: "SLIDER",
  DATETIME_PICKER: "DATETIME_PICKER",
});

export const TRACK_INPUT_TYPE = Object.freeze({
  [TRACK_FIELD_INPUT.TEXT_FIELD]: [TRACK_FIELD_TYPE.STRING, TRACK_FIELD_TYPE.INTEGER, TRACK_FIELD_TYPE.FLOAT],
  [TRACK_FIELD_INPUT.SELECT]: [TRACK_FIELD_TYPE.STRING, TRACK_FIELD_TYPE.INTEGER, TRACK_FIELD_TYPE.FLOAT],
  [TRACK_FIELD_INPUT.SLIDER]: [TRACK_FIELD_TYPE.INTEGER, TRACK_FIELD_TYPE.FLOAT],
  [TRACK_FIELD_INPUT.DATETIME_PICKER]: [TRACK_FIELD_TYPE.TIMESTAMP],
});

export const STEP_SYMBOL = Symbol("step");
