export const TRACK_TYPE = Object.freeze({
  TEXT: "TEXT",
  FLOAT: "FLOAT",
  INTEGER: "INTEGER",
});

export const TRACK_INPUT = Object.freeze({
  FIELD: "FIELD",
  SELECT: "SELECT",
  SLIDER: "SLIDER",
});

export const TRACK_TYPE_INPUT = Object.freeze({
  [TRACK_TYPE.TEXT]: [TRACK_INPUT.FIELD, TRACK_INPUT.SELECT],
  [TRACK_TYPE.FLOAT]: [TRACK_INPUT.FIELD, TRACK_INPUT.SELECT, TRACK_INPUT.SLIDER],
  [TRACK_TYPE.INTEGER]: [TRACK_INPUT.FIELD, TRACK_INPUT.SELECT, TRACK_INPUT.SLIDER],
});
